apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v3.2.0
          command: ["mlflow", "server"]
          args:
            - "--backend-store-uri=sqlite:///mlflow/mlflow.db"
            - "--default-artifact-root=/mlflow/artifacts"
            - "--host=0.0.0.0"
            - "--port=5000"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc
